services:
  employees-service:
    build:
      context: ./employees
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - employees/.env

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    env_file:
      - database/.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 2s
      timeout: 3s
      retries: 15

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - employees-service
      - postgres

volumes:
  postgres_data:
