services:
  employees-service:
    build:
      context: ./employees
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - employees/example.env

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped

    env_file:
      - database/example.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 2s
      timeout: 3s
      retries: 15

volumes:
  postgres_data:
