server {
    listen 80;
    absolute_redirect off;

    location /employees/ {
        proxy_pass http://employees-service:8080/;
    }

    location = /employees/swagger/ {
        return 302 /employees/swagger/index.html;
    }

    location /employees/swagger/ {
        proxy_pass http://employees-service:8080/swagger/;
        proxy_set_header Accept-Encoding "";
        sub_filter '\/swagger\/doc.json' '\/employees\/swagger\/doc.json';
    }

    location /reports/ {
        proxy_pass http://reports-service:8080/;
    }

    location = /reports/swagger/ {
        return 302 /reports/swagger/index.html;
    }

    location /reports/swagger/ {
        proxy_pass http://reports-service:8080/swagger/;
        proxy_set_header Accept-Encoding "";
        sub_filter '\/swagger\/doc.json' '\/reports\/swagger\/doc.json';
    }
}
